version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    expose:
      - '${DB_PORT_CONTAINER}'
    command: |2
      -p '${DB_PORT_CONTAINER}'

  server:
    depends_on:
      - db
    build:
      context: '.'
      dockerfile: server.dockerfile
    environment:
      PORT: '${SERVER_PORT_CONTAINER}'
      DB_HOST: db
      DB_PORT: '${DB_PORT_CONTAINER}'
      DB_NAME:
      DB_USER:
      DB_PASS:
    expose:
      - '${SERVER_PORT_CONTAINER}'

  client:
    depends_on:
      - server
    build:
      context: '.'
      dockerfile: client.dockerfile
      args:
        VITE_SERVER_BASE_URL: 'http://localhost:${SERVER_PORT_CONTAINER}/'
    ports:
      - '${CLIENT_PORT_HOST}:80'
