services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
    expose:
      - '${DB_PORT_CONTAINER}'
    command: |2
      -p '${DB_PORT_CONTAINER}'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: pg_isready -h db -U '${DB_USER}' -p '${DB_PORT_CONTAINER}'
      interval: 1s
      timeout: 10s
      retries: 30

  cache:
    image: redis:8-alpine
    expose:
      - '${CACHE_PORT_CONTAINER}'
    command: |2
      redis-server --port '${CACHE_PORT_CONTAINER}' --requirepass '${CACHE_PASS}' --save 60 1 --loglevel warning
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 60s
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 10s
      retries: 30

  greeter:
    build:
      context: '.'
      target: greeter
    environment:
      PORT: '${GREETER_PORT_CONTAINER}'
    expose:
      - '${GREETER_PORT_CONTAINER}'

  server:
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    build:
      context: '.'
      target: server
    environment:
      PORT: '${SERVER_PORT_CONTAINER}'
      DB_HOST: db
      DB_PORT: '${DB_PORT_CONTAINER}'
      DB_NAME:
      DB_USER:
      DB_PASS:
      CACHE_PROTOCOL: redis
      CACHE_HOST: cache
      CACHE_PORT: '${CACHE_PORT_CONTAINER}'
      CACHE_USER: 'default'
      CACHE_PASS: '${CACHE_PASS}'
      GREETER_HOST: greeter
      GREETER_PORT: '${GREETER_PORT_CONTAINER}'
    ports:
      - '${SERVER_PORT_HOST}:${SERVER_PORT_CONTAINER}'

  client:
    depends_on:
      - server
    build:
      context: '.'
      target: client
      args:
        CLIENT_PORT_CONTAINER:
        VITE_SERVER_BASE_URL: 'http://localhost:${SERVER_PORT_HOST}/'
    ports:
      - '${CLIENT_PORT_HOST}:${CLIENT_PORT_CONTAINER}'
